server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      url: mongodb://localhost:27017
      database: microservices

  config:
        import: optional:configserver:http://localhost:8085

#okta
okta:
  oauth2:
    issuer: https://dev-27732066.okta.com/oauth2/default
    audience: api://default


#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
